### ISSUE TITLE
Is there any impact for the api update

### ISSUE THREAD

**Issue by arthurtalkgoal** [pauldenotter/nautical#7]
https://developers.digitalocean.com/documentation/changelog/api-v2/actions-breaking-changes-upgrade-path/

```
Breaking changes in Action objects (March 20, 2015)

Date: February 20, 2015

Tagged In: API v2

Author Phillip Baker

All action objects, i.e. those returned by the /v2/actions, /v2/droplets/$ID/actions and /v2/images/$ID/actions endpoint now return a region_slug attribute, in addition to a region attribute. At 00:01 March 20, 2015 UTC, API v2 will start returning an embedded region object at the region attribute, not a slug
```

**Comment by pauldenotter** [comment]
Hi Arthur,

This will not break nautical, but might break your application! If you depend on the region attribute being a slug (string) you should refactor your application to use `region_slug` instead. Please update your application before March 20th to avoid any problems. The `region_slug` attribute is already available.

**Comment by arthurtalkgoal** [comment]
Hi @pauldenotter ,

Thanks for your advise! I almost deploying my codes to server. you saved me some debug time.

**Comment by pauldenotter** [comment]
Glad I could be of help! I will leave this issue open for a while so other users will notice.
